using System.Globalization;
using System.Text;
using System.Text.Json;
using Tomlyn;
using Tomlyn.Model;

namespace Romestead.ModValueEditor;

internal sealed class OverrideDocument
{
    public List<EntityHealthOverride> Entities { get; } = [];
    public List<ItemOverride> Items { get; } = [];

    public static OverrideDocument Load(string path)
    {
        var document = new OverrideDocument();
        if (!File.Exists(path))
        {
            return document;
        }

        var model = Toml.ToModel(File.ReadAllText(path));
        if (model.TryGetValue("entityHealth", out var rawEntities) && rawEntities is TomlTableArray entityArray)
        {
            foreach (var table in entityArray)
            {
                document.Entities.Add(new EntityHealthOverride
                {
                    BaseId = GetString(table, "baseId"),
                    MaxHealth = GetFloat(table, "maxHealth")
                });
            }
        }

        if (model.TryGetValue("items", out var rawItems) && rawItems is TomlTableArray itemArray)
        {
            foreach (var table in itemArray)
            {
                var item = new ItemOverride
                {
                    Id = GetString(table, "id"),
                    MaxStackSize = GetIntOrNull(table, "maxStackSize"),
                    Tier = GetIntOrNull(table, "tier")
                };

                if (table.TryGetValue("weapon", out var rawWeapon) && rawWeapon is TomlTable weaponTable)
                {
                    item.Weapon = new WeaponOverride
                    {
                        SwingTimer = GetFloatOrNull(weaponTable, "swingTimer"),
                        BaseAttackRange = GetFloatOrNull(weaponTable, "baseAttackRange"),
                        BaseKnockback = GetFloatOrNull(weaponTable, "baseKnockback"),
                        EnergyCost = GetFloatOrNull(weaponTable, "energyCost"),
                        SpecialEnergyCost = GetFloatOrNull(weaponTable, "specialEnergyCost"),
                        StunPower = GetFloatOrNull(weaponTable, "stunPower"),
                        MovementFactor = GetFloatOrNull(weaponTable, "movementFactor")
                    };

                    if (weaponTable.TryGetValue("damage", out var rawDamage) && rawDamage is TomlTableArray damageArray)
                    {
                        foreach (var damageTable in damageArray)
                        {
                            item.Weapon.Damage.Add(new DamageOverride
                            {
                                Type = GetString(damageTable, "type"),
                                Min = GetFloat(damageTable, "min"),
                                Max = GetFloat(damageTable, "max")
                            });
                        }
                    }
                }

                document.Items.Add(item);
            }
        }

        return document;
    }

    public void Save(string path)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, ToToml());
    }

    public string ToToml()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Romestead Mod Value Editor.");
        sb.AppendLine("# This file is distributable inside a .romod package.");

        foreach (var entity in Entities.Where(e => !string.IsNullOrWhiteSpace(e.BaseId)))
        {
            sb.AppendLine();
            sb.AppendLine("[[entityHealth]]");
            sb.AppendLine($"baseId = \"{Escape(entity.BaseId)}\"");
            sb.AppendLine($"maxHealth = {F(entity.MaxHealth)}");
        }

        foreach (var item in Items.Where(i => !string.IsNullOrWhiteSpace(i.Id)))
        {
            sb.AppendLine();
            sb.AppendLine("[[items]]");
            sb.AppendLine($"id = \"{Escape(item.Id)}\"");
            if (item.MaxStackSize is { } stack) { sb.AppendLine($"maxStackSize = {stack}"); }
            if (item.Tier is { } tier) { sb.AppendLine($"tier = {tier}"); }

            if (item.Weapon is { } weapon && weapon.HasAnyValue)
            {
                sb.AppendLine();
                sb.AppendLine("[items.weapon]");
                AppendFloat(sb, "swingTimer", weapon.SwingTimer);
                AppendFloat(sb, "baseAttackRange", weapon.BaseAttackRange);
                AppendFloat(sb, "baseKnockback", weapon.BaseKnockback);
                AppendFloat(sb, "energyCost", weapon.EnergyCost);
                AppendFloat(sb, "specialEnergyCost", weapon.SpecialEnergyCost);
                AppendFloat(sb, "stunPower", weapon.StunPower);
                AppendFloat(sb, "movementFactor", weapon.MovementFactor);

                foreach (var damage in weapon.Damage.Where(d => !string.IsNullOrWhiteSpace(d.Type)))
                {
                    sb.AppendLine();
                    sb.AppendLine("[[items.weapon.damage]]");
                    sb.AppendLine($"type = \"{Escape(damage.Type)}\"");
                    sb.AppendLine($"min = {F(damage.Min)}");
                    sb.AppendLine($"max = {F(damage.Max)}");
                }
            }
        }

        return sb.ToString();
    }

    private static string GetString(TomlTable table, string key) =>
        table.TryGetValue(key, out var raw) ? raw?.ToString() ?? "" : "";

    private static int? GetIntOrNull(TomlTable table, string key) =>
        table.TryGetValue(key, out var raw) ? Convert.ToInt32(raw, CultureInfo.InvariantCulture) : null;

    private static float? GetFloatOrNull(TomlTable table, string key) =>
        table.TryGetValue(key, out var raw) ? Convert.ToSingle(raw, CultureInfo.InvariantCulture) : null;

    private static float GetFloat(TomlTable table, string key) => GetFloatOrNull(table, key) ?? 0f;

    private static void AppendFloat(StringBuilder sb, string key, float? value)
    {
        if (value.HasValue)
        {
            sb.AppendLine($"{key} = {F(value.Value)}");
        }
    }

    internal static string F(float value) => value.ToString("0.####", CultureInfo.InvariantCulture);

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}

internal sealed class EntityHealthOverride
{
    public string BaseId { get; set; } = "";
    public float MaxHealth { get; set; } = 100f;
    public override string ToString() => $"Entity {Short(BaseId)} HP={OverrideDocument.F(MaxHealth)}";
    private static string Short(string value) => value.Length <= 8 ? value : value[..8];
}

internal sealed class ItemOverride
{
    public string Id { get; set; } = "";
    public int? MaxStackSize { get; set; }
    public int? Tier { get; set; }
    public WeaponOverride? Weapon { get; set; }
    public override string ToString() => $"Item {Id}";
}

internal sealed class WeaponOverride
{
    public List<DamageOverride> Damage { get; } = [];
    public float? SwingTimer { get; set; }
    public float? BaseAttackRange { get; set; }
    public float? BaseKnockback { get; set; }
    public float? EnergyCost { get; set; }
    public float? SpecialEnergyCost { get; set; }
    public float? StunPower { get; set; }
    public float? MovementFactor { get; set; }

    public bool HasAnyValue =>
        Damage.Count > 0 ||
        SwingTimer.HasValue ||
        BaseAttackRange.HasValue ||
        BaseKnockback.HasValue ||
        EnergyCost.HasValue ||
        SpecialEnergyCost.HasValue ||
        StunPower.HasValue ||
        MovementFactor.HasValue;
}

internal sealed class DamageOverride
{
    public string Type { get; set; } = "Piercing";
    public float Min { get; set; }
    public float Max { get; set; }
    public override string ToString() => $"{Type} {OverrideDocument.F(Min)}-{OverrideDocument.F(Max)}";
}

internal sealed class PreviewMetadata
{
    public Dictionary<string, PreviewEntry> Entries { get; init; } = new(StringComparer.OrdinalIgnoreCase);

    public static PreviewMetadata Load(string path)
    {
        if (!File.Exists(path))
        {
            return new PreviewMetadata();
        }

        try
        {
            return JsonSerializer.Deserialize<PreviewMetadata>(File.ReadAllText(path)) ?? new PreviewMetadata();
        }
        catch
        {
            return new PreviewMetadata();
        }
    }

    public void Save(string path)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, JsonSerializer.Serialize(this, new JsonSerializerOptions { WriteIndented = true }));
    }
}

internal sealed class PreviewEntry
{
    public string ImagePath { get; set; } = "";
    public int FrameWidth { get; set; } = 32;
    public int FrameHeight { get; set; } = 32;
    public int FrameIndex { get; set; }
}
